"""Add restricted_times to cabins

Revision ID: 0e925bffaadc
Revises: 876ad3c13b0b
Create Date: 2025-05-16 16:55:35.333991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e925bffaadc'
down_revision: Union[str, None] = '876ad3c13b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabins', sa.Column('restricted_times', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cabins', 'restricted_times')
    # ### end Alembic commands ###
